### PR TITLE
Use read-only personal access token to replace clientID & clientSecret

### PR DESCRIPTION
**Pull request by geektutu**
#343 github suggests use basic auth to replace origin clientid & clientsecret auth
reference: https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/\#authenticating-using-query-parameters

**Before submitting a pull request**, please make sure the following is done:

1. [Fork the repository](https://github.com/gitalk/gitalk/fork) and create your branch from master.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (npm test).
5. Make sure your code lints (npm run lint).
6. Commit your changes (git commit) [Commit Message Format Reference](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines).

### CODE REVIEW

**Comment by draveness** [comment]
How can we generate read-only access token? We don't have that option.

**Comment by Mabbs** [comment]
> How can we generate read-only access token? We don't have that option.

Nothing to select

**Comment by geektutu** [comment]
@draveness goto [343](https://github.com/gitalk/gitalk/issues/343#issuecomment-581758733)

**Comment by fletchto99** [comment]
See my comment in https://github.com/gitalk/gitalk/issues/343#issuecomment-581773838 - I'm not sure this is the best approach to the problem. It would probably be better to use anonymous requests if the user isn't logged in.

**Comment by draveness** [comment]
> See my comment in [#343 (comment)](https://github.com/gitalk/gitalk/issues/343#issuecomment-581773838) - I'm not sure this is the best approach to the problem. It would probably be better to use anonymous requests if the user isn't logged in.

Access token could be optional to the user. If they provide the access token, they won't meet the rate limit problem

**Comment by draveness** [comment]
BTW: do we have active maintainers here? If not, we have to fork and make our own change. 😂

**Comment by geektutu** [comment]
I have updated the PR to make access token be optional to the user. [diff](https://github.com/gitalk/gitalk/pull/344/commits/8c4dfdcf1d7d4abccc02bdd03442619d89b488e4#diff-b75da62042ff3385546ca75d01d07585)

Provide empty Authorization header is OK

```bash
curl -H "Authorization:" https://api.github.com/rate_limit 
{
  "resources": {
    "core": {
      "limit": 60,
      "remaining": 56,
```

but leaving wrong or empty accessToken does't work.

```bash
curl -H "Authorization:token" https://api.github.com/rate_limit
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}
```

By the way, If there is no active maintainers, my fork repo is [geektutu/gitalk](https://github.com/geektutu/gitalk), here is regenerated [gitalk.min.js](https://geektutu.github.io/hexo-theme-geektutu/js/gitalk.min.js)

**Comment by draveness** [comment]
> * Here is regenerated [gitalk.min.js](https://geektutu.github.io/hexo-theme-geektutu/js/gitalk.min.js)

This is GREAT! Thanks for your work.

**Comment by booxood** [comment]
@geektutu Thank you very much for PR. Don’t commit 'dist' next time if you can.

**Comment by fletchto99** [comment]
Instead of using a PAT I found it is possible to sent the client ID and client secret as basic authorization traders. I'd like to propose we do that instead. I will think using a PAT poses a much larger risk, even if it is read only.

**Pull request merged**
